pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://jitpack.io") }
        maven { url 'https://devrepo.kakao.com/nexus/content/groups/public/' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://jitpack.io") }
        maven { url 'https://devrepo.kakao.com/nexus/content/groups/public/' }
        maven {
            url 'https://repository.map.naver.com/archive/maven'
        }
    }
}

rootProject.name = "EasyLaw"
include ':app'